### PR TITLE
WIP; SQL for abrfc-qpe-01h

### PR DESCRIPTION
**Pull request by brettpalmberg**

### CODE REVIEW

**Comment by adamscarberry** [comment]
@brettpalmberg added `acceptable_timedelta` to your migration.  Be sure to pull latest.

**Comment by brettpalmberg** [comment]
> @brettpalmberg added `acceptable_timedelta` to your migration. Be sure to pull latest.

Awesome, thanks!  Wilco.

**Comment by brettpalmberg** [comment]
> > @brettpalmberg added `acceptable_timedelta` to your migration. Be sure to pull latest.
> 
> Awesome, thanks! Wilco.

@adamscarberry , I accidentally wrote over addition of `acceptable_timedelta` with my latest rebase and push. _My bad :)_. If you still have your changes handy, can you push this branch again?

**Comment by adamscarberry** [comment]
All good.  added back

**Pull request merged**
