### PR TITLE
Develop to stable merge

### PR DESCRIPTION
**Pull request by adamscarberry**
update geoproces - https://github.com/USACE/cumulus/issues/414

fix aprfc qpe - inches to MM - https://github.com/USACE/cumulus/issues/380

### CODE REVIEW

**Comment by adamscarberry** [comment]
@msweier I hope to merge this today.  It looks like it included your APRFC sql migration from inches to MM.  Have you confirmed that this is correct and that it fixed the issue before I merge this to stable?

**Comment by msweier** [comment]
> @msweier I hope to merge this today. It looks like it included your APRFC sql migration from inches to MM. Have you confirmed that this is correct and that it fixed the issue before I merge this to stable?

@adamscarberry, I just checked the dev server, and we are good to go. The grids will need to be backfilled as far as we can go to correct the units. 
image

**Comment by adamscarberry** [comment]
Test MRMS QPE pass 2 and WPC QPF using develop vs stable.  Results from packager dss were same.

**Comment by adamscarberry** [comment]
@msweier Grids should not need backfilled.  The geoproc processor was good, meaning the tifs are still good (in their native format).  By changing the units in the sql, it will correct the packager conversion for DSS with any NEW downloads after it is applied in stable.

**Pull request merged**
