### PR TITLE
412 qa review nwo grid extents

### LINKED ISSUE #412: [QA Review]: NWO Grid Extents
Email from Zach H. (NWO) on 6/20/24

We are hoping to make some deletions and one addition if possible. For the attached shapefile, can we get a watershed in the NWO office and call it “NWO - LwrYellowstone”? 

we also believe that the following can be deleted:

- NWO – Bighorn River (not to be confused with "Bighorn")
- NWO – Fort Peck to Garrison
- NWO – Above Fort Peck 

[NWO_LwrYellowstone.7z.txt](https://github.com/user-attachments/files/15919646/NWO_LwrYellowstone.7z.txt)

Note to assignee: 

Name should be: "LwrYellowstone" ("NWO - " is just a display view in the UI)

### PR DESCRIPTION
**Pull request by katfeingold**
Added the Lower Yellowstone watershed extents 
DID NOT delete anything.

### CODE REVIEW

**Comment by Enovotny** [comment]
change this to goto develop and not stable.

**Comment by Enovotny** [comment]
also try to remove the .41 and .42 files from the commit.  not sure why they are showing up if you didn't update them.  you should be able to just do git rm filename

**Comment by katfeingold** [comment]
OK, shifted to develop, and I think .41 and .42 were removed, not sure why they were with them. I hope that worked at least.
Thanks!

**Comment by katfeingold** [comment]
Adjusted the name and pushed it up. Thanks

**Pull request closed without merging**
