### PR TITLE
Fix aprfc qpe units from mm to in

### PR DESCRIPTION
**Pull request by msweier**
Checked totals in MMRS with DSS file for July 10 1200-1800 
image

QPF units appeared to be correctly coded as in

### CODE REVIEW

**Review by Enovotny — APPROVED** [review]

**Comment by adamscarberry** [comment]
@msweier @Enovotny  This migration is not correct.  `label` should not have been used in the where clause.  If you want to use that value in the where you should use `slug`.  Alternatively you can use the `id`.

image


For clarification, this did nothing in develop.

Your commit message said fix units from mm to in, but your unit_id is `mm` which makes sense because it's already inches in cumulus stable. Assuming typo there.


I can manually back out the migration in the develop database (flyway record) if you want to try this again.  Don't try to change the migration and submit until I do this as it will not work.

**Comment by msweier** [comment]
> @msweier @Enovotny This migration is not correct. `label` should not have been used in the where clause. If you want to use that value in the where you should use `slug`. Alternatively you can use the `id`.
> 
> image
> For clarification, this did nothing in develop.
> 
> Your commit message said fix units from mm to in, but your unit_id is `mm` which makes sense because it's already inches in cumulus stable. Assuming typo there.
> 
> I can manually back out the migration in the develop database (flyway record) if you want to try this again. Don't try to change the migration and submit until I do this as it will not work.

Whoops, I meant to use slug. This also probably means the problem is somewhere else. Will have to do more digging. Thanks.

**Comment by adamscarberry** [comment]
@msweier Did you mean to change `in` to `mm`?  If so that can still be done.  Just wanting to verify.  Hoping someone has verified the product source comes in as `mm` if we're changing the unit.

**Comment by msweier** [comment]
> @msweier Did you mean to change `in` to `mm`? If so that can still be done. Just wanting to verify. Hoping someone has verified the product source comes in as `mm` if we're changing the unit.

@adamscarberry the product does appear it comes in mm, not inches, but I checked the DSS file with this change (which did nothing) with the MRMS web product and the spot totals matched. So I've got to look into this more. It's been reported there's a bust in the combined QPF and QPE, so maybe there's something going on with the QPF too.

**Pull request merged**
