### PR TITLE
411 product additional florida extents map

### LINKED ISSUE #411: [PRODUCT]: Additional Florida Extents map
## Product Source (URL Preferred)
Extent Addition for the state of Florida - SAJ would like this added as an option for extents in Cumulus

## Product Description
[FloridaExtents.zip](https://github.com/user-attachments/files/15794777/FloridaExtents.zip)

## Product Format

- [ ] Geotiff
- [ ] Grib2
- [ ] NetCDF
- [X ] Other (Please provide description below)

#### Format Description

Shapefile

### PR DESCRIPTION
**Pull request by katfeingold**
This adds the full extent of Florida for SAJ.
Huge thank you to Adam for his help and handholding me on my first ticket.

### CODE REVIEW

**Comment by adamscarberry** [comment]
Hey @katfeingold   Glad to help.

Two things:

1. I just beat you with a new watershed change for SAD and NAD, which means I used migrations number 2.41 and 2.42.  You will need to change yours to 2.43
2. Please change this PR to merge into `develop` first.  This will deploy to the `develop` version of cumulus.  Then when that looks ok, you can merge `develop` into `stable`.

**Comment by adamscarberry** [comment]
Please include issue within PR when possible.  example: https://github.com/USACE/cumulus/issues/411

**Comment by katfeingold** [comment]
Hey Adam,

So first, I’m sorry about this, but here is the point where you all will need to do some handholding.  Again Super sorry for this.
I have no experience in this other than the setup, I did this following a video that Eric sent me. I am trying to learn, but unfortunately, I will take a little bit more explanation to fix what you are asking.
I would ask Eric, but he is on leave this week.

I am going to try reexplaining what you ask so I know I’m not messing something up before I try again.
I need to change the number at the front of my file from its current to 2.43. In order to do that do I need to create a new branch? If not, how to I adjust the current branch.
I’m not quite sure how to change it to merge with “develop” I thought I had originally when I branched it, but from your comment I think I messed that up.

Also your addiitonal comment, about haing the PR when possible, I’m guessing you are refering to the pull request, but um, I’m not entierlly shure where that number is. If you could point me in that direction as well I would greatly appreciate it.

Again sorry for all this, thank you for your patience with me.

Respectfully,

Kathryn Feingold
Water Management Systems Division
Hydrologic Engineering Center
U.S. Army Corps of Engineers
(912) 239-0275

From: Adam Scarberry ***@***.***>
Sent: Tuesday, August 6, 2024 4:46 PM
To: USACE/cumulus-api ***@***.***>
Cc: Feingold, Kathryn A CIV IWR ***@***.***>; Mention ***@***.***>
Subject: [Non-DoD Source] Re: [USACE/cumulus-api] 411 product additional florida extents map (PR #486)


Hey @katfeingold<Blockedhttps://github.com/katfeingold> Glad to help.

Two things:

  1.  I just beat you with a new watershed change for SAD and NAD, which means I used migrations number 2.41 and 2.42. You will need to change yours to 2.43
  2.  Please change this PR to merge into develop first. This will deploy to the develop version of cumulus. Then when that looks ok, you can merge develop into stable.

**Comment by adamscarberry** [comment]
@katfeingold I'll try to answer here, but am willing to do so over a call.

1. To fix the migration number, just change the filename in your existing local branch `411-product-additional-florida-extents-map`, then commit and push back to github.
2. To fix the branch you will be merging into on this PR, click `Edit` at top of this page.  Then using the dropdown change the branch to `develop`

**Pull request closed without merging**
