### PR TITLE
call log_dataset() only at DEBUG level; fix zwrite_record call param …

### PR DESCRIPTION
**Pull request by adamscarberry**
…name

mentioned in: https://github.com/USACE/cumulus/issues/257

### CODE REVIEW

**Comment by adamscarberry** [comment]
quick and dirty tests showed this change reduced an 8 sec download to 2 sec.

**Review by jeffsuperglide — APPROVED** [review]

**Comment by brettpalmberg** [comment]
@adamscarberry, @jeffsuperglide, this looks good. One additional change (admittedly not something that was introduced in this PR). On Line 43, `gdal_dataset = None`.  I think this should be removed. gdal_dataset is passed to the function (and then subsequently used further down in the script). Setting it to `None` here inside the function seems problematic.

**Review by brettpalmberg — CHANGES_REQUESTED** [review]
@adamscarberry, @jeffsuperglide, this looks good. One additional change (admittedly not something that was introduced in this PR). On Line 43, `gdal_dataset = None`. I think this should be removed. `gdal_dataset` is passed to the function (and then subsequently used further down in the script). Setting it to `None` here inside the function seems problematic.

**Comment by adamscarberry** [comment]
> @adamscarberry, @jeffsuperglide, this looks good. One additional change (admittedly not something that was introduced in this PR). On Line 43, `gdal_dataset = None`. I think this should be removed. `gdal_dataset` is passed to the function (and then subsequently used further down in the script). Setting it to `None` here inside the function seems problematic.

makes sense.  fixed

**Review by brettpalmberg — COMMENTED** [review]
Looks good!

**Review by brettpalmberg — APPROVED** [review]

**Pull request merged**
