### PR TITLE
update slug, label, dss_fpart and desc on NDGD airtemp and precip

### PR DESCRIPTION
**Pull request by adamscarberry**
The name should make more sense.

It will now show up as `NDGD RTMA PRECIP 1hr`

F-Part changes from `NDGD-LEIA98` to `NDGD-RTMA`.

Airtemp changes too.

### CODE REVIEW

**Comment by adamscarberry** [comment]
@jeffsuperglide DSS F-Part may be a little disruptive for extract lists, but I don't think slug will matter.  Any concerns?

**Comment by jeffsuperglide** [comment]
Processor name will have to change matching the new slug?

**Comment by adamscarberry** [comment]
```
outfile_list = [
        { "filetype": "ndgd-leia98-precip", "file": cog, "datetime": dt.replace(tzinfo=timezone.utc).isoformat(), "version": None },
    ]
```

Is that the product slug used for filetype?

**Comment by jeffsuperglide** [comment]
The filetype and processor name (name.py) are the same.  That name.py is the "plugin" name.

**Comment by adamscarberry** [comment]
slug changes backed out

**Pull request merged**
