### PR TITLE
Fix aprfc-qpf-06hr units Develop

### PR DESCRIPTION
**Pull request by msweier**
DSS units are now mm as expected in develop, but when comparing develop branch dss files from before fix, slight differences exist in the grids. This could be from from versioning?  Even stranger, downloads for the same timewindow produced different data temporal extents in dss files. If this is known or expected, it can be merged.
image

image

image
image

### CODE REVIEW

**Comment by msweier** [comment]
@Enovotny, the units are fixed. I tried to replicate the issue I saw above with the different temporal extents and slight differences in the file, but I could not today. Everything worked fine. I recommend merging pull request.

**Review by Enovotny — APPROVED** [review]

**Review by Enovotny — APPROVED** [review]

**Comment by adamscarberry** [comment]
Hold off on this.  The migration that was being suggested was a duplicate of `V2.40.0__fix_aprfc_qpe_units.sql`

https://github.com/USACE/cumulus/issues/425

**Comment by adamscarberry** [comment]
This is already in stable:

image

**Comment by adamscarberry** [comment]
replaced PR with https://github.com/USACE/cumulus-api/pull/499

**Pull request closed without merging**
