### PR TITLE
ncep stage4 mosaic: acquirable, suite, product sql

### PR DESCRIPTION
**Pull request by brettpalmberg**

### CODE REVIEW

**Comment by brettpalmberg** [comment]
Hey @adamscarberry, when convenient, can you take a look at this SQL? Thinking we can both work off of this branch.

Related to USACE/cumulus#255

**Comment by adamscarberry** [comment]
Recommend adding "QPE" somewhere in the label.  If we might want the Stage4 PR product in the future, we may want to add "CONUS" to this label as well.  Tags can indicate this in web ui, but not CAVI.

**Comment by brettpalmberg** [comment]
> Recommend adding "QPE" somewhere in the label. If we might want the Stage4 PR product in the future, we may want to add "CONUS" to this label as well. Tags can indicate this in web ui, but not CAVI.

Good call. I'll make these changes and cc you to take a second look when convenient.

**Comment by brettpalmberg** [comment]
@adamscarberry, how does this look?  Changes are reflected in feature/255-product-national-qpe-mosaic. Relevant SQL: https://github.com/USACE/cumulus-api/pull/331/commits/a99c05cf95ee55d45dfef8c3b9e0821291a52ea7#diff-2e2ca4827a1511628f04436e8170ae1c5f61aacc809883388e707a7e1cddea1a

**Review by adamscarberry — APPROVED** [review]

**Pull request merged**
