### PR TITLE
async_geoprocess use HTTP API for data updates; Eliminate DB Connection

### PR DESCRIPTION
**Pull request by brettpalmberg**
* [api] Update Go Echo Version to support array scanning
* [api] Migrate to JWT Library github.com/golang-jwt/jwt; Eliminates security warnings; Allows Echo version upgrade
* [api] Add Endpoint GET /product_slugs
* [api] Add Endpoint POST /productfiles
* [api] go get -u; go mod tidy
* [async_geoprocess] Convert data updates from Database Connection to HTTP calls
* [async_geoprocess] Modify processors to use RFC3339 datetimes; Required for Go Echo's strict time.Time scanning,
  which requires RFC3339 date strings in POST body
* [async_geoprocess] Start unittest file geoprocess_worker/test_helpers.py
* Remove now-unnecessary environment variables from docker-compose.yml
* Misc Other Changes

### CODE REVIEW

**Comment by adamscarberry** [comment]
Tested WPF QPF and SNODAS locally.  Both created tifs with no problem and wrote records to database as expected.

**Review by adamscarberry — APPROVED** [review]
local test of two products worked as expected.  suggest merging.

**Comment by brettpalmberg** [comment]
Thanks @adamscarberry

**Comment by brettpalmberg** [comment]
closes USACE/cumulus#139

**Pull request merged**
