### PR TITLE
Feature/dss parameter domain

### LINKED ISSUE #275: [FEATURE REQUEST]: Add DSS Datatype to `GET /products` Endpoint
## Feature Request Type
- [ ] ***User Interface (UI)***
- [x] ***Application Programming Interface (API)***

### LINKED ISSUE #276: [FEATURE REQUEST]: Add Cumulus API Version to an Endpoint
## Feature Request Type
- [ ] ***User Interface (UI)***
- [x] ***Application Programming Interface (API)***

Adding semantic versioning returned by an api endpoint will help client-side code feature-flag based on running version of the Cumulus API.  e.g. `{ "version": "1.3" }`. Consider semver: https://semver.org/. Also consider only providing `<major>.<minor>`.

### PR DESCRIPTION
**Pull request by brettpalmberg**
closes USACE/cumulus#275

closes USACE/cumulus#276 (version added to endpoint `/health`)

### CODE REVIEW

**Comment by brettpalmberg** [comment]
> [brettpalmberg](https://github.com/brettpalmberg) changed the base branch from stable to develop [1 minute ago](https://github.com/USACE/cumulus-api/pull/360#event-7197514683)

YOLO! Apparently I merge feature branches right into stable these days 😂 @adamscarberry. Switched base branch to develop.

**Comment by adamscarberry** [comment]
Testing this now.

**Comment by adamscarberry** [comment]
Tested locally by checking database products table and view.  Acquired random data and created DSS file.  Viewed DSS records (found other issues not related).  Newman tests ran without issue.

I can't say it was a completely thorough review, but I didn't find any breaking changes.

**Review by adamscarberry — APPROVED** [review]

**Comment by brettpalmberg** [comment]
Thanks @adamscarberry! Merging to `develop` now.

**Comment by brettpalmberg** [comment]
Something went awry in `develop` when attempting to run the R__04_views_products.sql.  Going to run SQL to DROP VIEW v_product (then recreate).

image

**Comment by brettpalmberg** [comment]
Note for the future, remember to `DROP VIEW` before altering underlying tables.  In this case, following should have been added to the top of migration sql/V2.08.00__dss_datatypes.sql:

```
DROP VIEW v_productfile;
DROP VIEW v_product;
DROP VIEW v_download_request;
```

Fixed after the fact here: https://github.com/USACE/cumulus-api/commit/5bee2a412418864edd56b0248c6d2c86eb2ec8f5

And here (must include IF EXISTS for case when standing up a new database and repeatable migrations in sql/common/R__* have not run yet) https://github.com/USACE/cumulus-api/pull/363/commits/e9a60b33bdb0dc593cbe9e8baea8e347144c101f

**Pull request merged**
